# Generated by Django 5.1.15

from django.db import migrations, models


def seed_categories(apps, _schema_editor):
    Category = apps.get_model("listings", "Category")
    categories = [
        ("Telegram bots", "telegram-bots"),
        ("E-commerce", "ecommerce"),
        ("Automation scripts", "automation-scripts"),
        ("Web apps", "web-apps"),
        ("Mobile apps", "mobile-apps"),
        ("APIs & backends", "apis-backends"),
    ]
    for name, slug in categories:
        Category.objects.get_or_create(name=name, defaults={"slug": slug})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Incremented when project detail page is viewed",
            ),
        ),
        migrations.RunPython(seed_categories, noop),
    ]
