# Generated by Django 5.1.15 on 2026-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_project_download_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the seller accepted the terms during submission",
                null=True,
            ),
        ),
    ]
