# Generated by Django 5.1.15 on 2026-07-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_project_terms_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#3fd68c",
                help_text="Hex color (e.g. #3fd68c) used to theme the product page",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="banner_image",
            field=models.URLField(
                blank=True,
                help_text="Wide hero banner shown at the top of the product page",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Pin to the top of the marketplace as an editor's pick"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="highlights",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of short selling-point strings shown as bullets",
            ),
        ),
    ]
