# Generated by Django 6.0.6 on 2026-07-29 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_project_average_rating_project_rating_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "-created_at"], name="listings_pr_status_b8b613_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["seller", "status"], name="listings_pr_seller__472edf_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["category", "status"], name="listings_pr_categor_f1c9e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["featured"], name="listings_pr_feature_630e13_idx"),
        ),
    ]
