# Generated by Django 6.0.6 on 2026-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_add_security_audit_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="banner_image",
            field=models.TextField(
                blank=True,
                help_text="Wide hero banner shown at the top of the product page",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
