# Generated by Django 6.0.6 on 2026-07-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_projectqa"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text="Detailed markdown description shown on the project detail page",
                null=True,
            ),
        ),
    ]
