# Generated by Django 5.1.15 on 2026-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_github_token_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Optional chat ID for notifications",
                max_length=100,
                null=True,
            ),
        ),
    ]
