# Generated by Django 6.0.6 on 2026-07-27 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_legal_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Phone number must be 7-15 digits, optionally starting with '+' or '1'."
                        ),
                        regex="^\\+?1?\\d{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
