# Generated by Django 6.0.6 on 2026-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_full_legal_name_user_phone_number_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="True when phone_number was verified via Telegram contact sharing.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the most recent phone verification.", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("phone_number"),
                condition=models.Q(("phone_verified", True)),
                name="unique_verified_phone",
            ),
        ),
    ]
