# Generated by Django 5.1.15 on 2026-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_options_user_phone_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the most recent login", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address at account creation", null=True
            ),
        ),
    ]
