# Generated by Django 6.0.6 on 2026-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_ip_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
