# Generated by Django 5.1.15 on 2026-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Texnologiya va startaplar"),
                    ("trade", "Savdo va xizmatlar"),
                    ("media", "Shaxslar va media"),
                    ("edu", "Ta'lim va karyera"),
                    ("ai", "AI"),
                ],
                default="tech",
                help_text="Used by the frontend category tabs/filter.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="clicks",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Outbound visits to the entry's domain (incremented by the public click endpoint).",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
