# Generated by Django 5.1.15 on 2026-08-13 04:36

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0001_build_payouts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutFeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Percentage deducted from each seller payout request.",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Withdrawal fee",
                "verbose_name_plural": "Withdrawal fees",
            },
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="payout_fee_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="payout_fee_percent",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
        ),
    ]
