# Generated by Django 6.0.6 on 2026-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("copyright", "Copyright Violation"),
                    ("malicious_code", "Malicious Code"),
                    ("misleading", "Misleading Description"),
                    ("duplicate", "Duplicate Listing"),
                    ("spam", "Spam"),
                    ("inappropriate", "Inappropriate"),
                    ("fraud", "Fraud"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
