# Generated by Django 6.0.6 on 2026-08-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0011_project_long_description"),
        ("moderation", "0002_alter_report_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICodeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed (Safe & Matching)"),
                            ("flagged_malware", "Flagged Malware"),
                            ("description_mismatch", "Description Mismatch"),
                            ("error", "Analysis Error"),
                        ],
                        default="passed",
                        max_length=30,
                    ),
                ),
                (
                    "is_malware",
                    models.BooleanField(
                        default=False,
                        help_text="True if malicious patterns, obfuscation, or backdoors were detected",  # noqa: E501
                    ),
                ),
                (
                    "malware_score",
                    models.IntegerField(
                        default=0,
                        help_text="Malware risk score from 0 (clean) to 100 (high severity malware)",  # noqa: E501
                    ),
                ),
                (
                    "match_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Match score (0-100%) between code logic and project title/description",  # noqa: E501
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Concise summary of AI review findings", null=True
                    ),
                ),
                (
                    "malware_findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of specific suspicious code patterns or threats detected",
                    ),
                ),
                (
                    "description_analysis",
                    models.TextField(
                        blank=True, help_text="Explanation of description match score", null=True
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="Model Studio model that successfully performed the review",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Total tokens consumed for prompt and completion"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw structured JSON response returned by the AI",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_code_reviews",
                        to="listings.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_code_reviews_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
    ]
