# Generated by Django 6.0.6 on 2026-07-29 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_add_security_audit_indexes"),
        ("orders", "0001_build_orders_payments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["seller", "status"], name="orders_orde_seller__c90b9c_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["buyer", "status"], name="orders_orde_buyer_i_4389c9_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "-paid_at"], name="orders_orde_status_64a28e_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "type", "-created_at"], name="orders_tran_user_id_efebd8_idx"
            ),
        ),
    ]
