# Generated by Django 6.0.6 on 2026-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_add_security_audit_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
