# Generated by Django 6.0.6 on 2026-07-29 06:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "phone_number",
                    models.CharField(
                        help_text=(
                            "Phone number from Telegram contact "
                            "(verified as belonging to sender)."
                        ),
                        max_length=20,
                    ),
                ),
                ("telegram_chat_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed verification attempts."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="notificatio_user_id_9bc14f_idx"
                    ),
                    models.Index(
                        fields=["expires_at", "used"], name="notificatio_expires_4c99f8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramLinkingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Populated when the token is consumed by the bot.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed", models.BooleanField(default=False)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_linking_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="notificatio_token_73fdee_idx"),
                    models.Index(
                        fields=["expires_at", "consumed"], name="notificatio_expires_3a8031_idx"
                    ),
                ],
            },
        ),
    ]
